# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
null_vector = np.zeros(10)
null_vector[5] = 1
null_vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
random_vector = np.random.randint(10,49, size=10)
random_vector

array([36, 13, 27, 12, 29, 22, 46, 17, 42, 44])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [9]:
random_vector_reversed = random_vector[::-1]
random_vector_reversed

array([44, 42, 17, 46, 22, 29, 12, 27, 13, 36])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
matrix_3x3 = np.random.randint(0,8, size=(3,3))
matrix_3x3

array([[6, 4, 6],
       [2, 5, 2],
       [0, 4, 2]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [15]:
x = np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4]),)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [26]:
a = np.random.rand(3,3)
a

array([[0.45786987, 0.78174285, 0.86559834],
       [0.05070018, 0.48574843, 0.07890511],
       [0.88660179, 0.56616151, 0.79938098]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [28]:
a = np.random.rand(10,10)
print(a)
print('min:', np.amin(a))
print('max:', np.amax(a))

[[0.43449774 0.51234803 0.94552759 0.78459207 0.75047179 0.8907446
  0.7710143  0.18110069 0.64343699 0.7067284 ]
 [0.37677244 0.7801882  0.48501533 0.78075558 0.89243962 0.35043476
  0.22823644 0.09857471 0.4046379  0.0166198 ]
 [0.89591153 0.43416619 0.28010698 0.34363952 0.20289184 0.59753595
  0.57643389 0.05649434 0.30136109 0.45922814]
 [0.23094571 0.16260309 0.89599457 0.91162951 0.3578578  0.65394158
  0.46042172 0.24484582 0.38012602 0.44585046]
 [0.85212502 0.84788163 0.73567812 0.01746156 0.17271931 0.58874499
  0.38243362 0.19448775 0.57482718 0.17996794]
 [0.96983765 0.9092705  0.8287023  0.27243713 0.03362949 0.15098068
  0.08736738 0.13935508 0.39395392 0.25533156]
 [0.49410919 0.14240951 0.12053804 0.6280787  0.13238207 0.83202683
  0.6718741  0.9534461  0.80447292 0.09449161]
 [0.17213581 0.4613004  0.48936394 0.17829863 0.58830202 0.77607729
  0.25777478 0.72867561 0.10386717 0.54159864]
 [0.21305675 0.52710018 0.53068234 0.4932916  0.35541485 0.51408821
  0.13322321 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [31]:
a = np.random.rand(30)
print(a)
print(np.mean(a))

[0.13900547 0.43121903 0.04671062 0.15428048 0.14240557 0.43550214
 0.00939801 0.75704634 0.97520086 0.20155446 0.01607808 0.73140359
 0.28987752 0.97114802 0.7660593  0.21549842 0.31241982 0.35929959
 0.67371993 0.32113208 0.80453805 0.81274796 0.69048199 0.18740693
 0.78929732 0.97471009 0.73892943 0.44415134 0.17850758 0.1788568 ]
0.4582862267088875


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [34]:
a = np.ones((3,3))
a[1,1] = 0
a

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [38]:
b = np.pad(a, pad_width=1)
b

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [54]:
a = np.zeros((5,5))
a[[1,2,3,4],[0,1,2,3]] = [1,2,3,4]
a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [65]:
np.unravel_index(99,(6,7,8))


(1, 5, 3)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [75]:
a = np.random.rand(5,5)*10
norm = np.linalg.norm(a)
normal_a = a/norm
print(norm)
print(a)
print(normal_a)


29.642562639775033
[[7.64883523 6.84732215 5.54167943 6.45530851 1.33439458]
 [6.84862797 9.9821903  9.20616547 6.24823995 3.20129728]
 [9.02804725 0.98976477 3.14030518 3.42328895 4.76931055]
 [9.52704088 5.15391316 3.53548773 6.28342276 0.28353692]
 [8.70987798 4.68762985 1.52040691 3.39882496 3.26171139]]
[[0.25803556 0.2309963  0.18695008 0.21777161 0.04501617]
 [0.23104035 0.33675193 0.31057252 0.21078609 0.10799664]
 [0.30456366 0.03338999 0.10593906 0.11548559 0.160894  ]
 [0.32139734 0.17386868 0.11927065 0.21197299 0.0095652 ]
 [0.29383013 0.15813848 0.05129135 0.11466029 0.11003473]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [83]:
a = np.array([1,2,3,4,5,6,7,8,9])
np.negative(a, where=(a > 3) & (a < 8))


array([ 1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 29. How to round away from zero a float array ? (★☆☆)

In [85]:
a = np.random.rand(10)*100
np.round(a,0)

array([45., 13., 29., 24., 67.,  0., 49., 20., 76., 22.])

#### 30. How to find common values between two arrays? (★☆☆)

In [89]:
a = np.arange(10)
b = np.array([1,3,5,7,9])
np.intersect1d(a,b)


array([1, 3, 5, 7, 9])

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [91]:
False

False

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [93]:
def array_generator():
    interger_list = []
    for i in range(10):
        interger_list.append(i)
        
    array = np.array(interger_list)
    return array

array_generator()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [95]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [97]:
random_vector = np.random.rand(10)
sorted_vector = np.sort(random_vector)
sorted_vector

array([0.08291002, 0.10511102, 0.36032629, 0.4023161 , 0.46980615,
       0.69677083, 0.70246031, 0.95526998, 0.97382353, 0.98894275])

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [114]:
a = np.random.randint((2,2))
print(a)
b = np.random.randint((2,2))
print(b)
np.array_equal(a,b)

[0 0]
[1 1]


False

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [153]:
random_vector = np.random.randint(10, size=10)
print(random_vector)
max_replaced_vector = np.copy(random_vector)
max_replaced_vector[np.argmax(max_replaced_vector)] = 0
print(max_replaced_vector)




[2 4 0 7 5 8 0 1 6 4]
[2 4 0 7 5 0 0 1 6 4]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [150]:
def find_closest(array, value):
    array = np.asarray(array)
    idx = np.abs(array - value).argmin()
    return array[idx]

array = np.random.randint(100, size=10)
print(array)
print(find_closest(array, 4))

[55 67 48 99 94 23 26 10  7 57]
7


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [157]:
a = np.arange(10, dtype="float32")
print(a)
b = a.astype('int32')
b

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 59. How to sort an array by the nth column? (★★☆)

In [169]:
def sort_array(array, column):
    """Sort array by specified column"""
    
    array = np.asarray(array)
    idx = a[:,column].argsort()
    return array[idx]

a = np.random.randint(10, size=(3,3))
print(a)

column_to_sort_by = 2

sort_array(a, column_to_sort_by)

[[1 8 0]
 [4 9 8]
 [2 3 5]]


array([[1, 8, 0],
       [2, 3, 5],
       [4, 9, 8]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [172]:
a = np.random.randint(10, size=(5,5))
(~a.any(axis=0)).any()

False

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [210]:
def add_zeros(array):
    array = np.asarray(array)
    array_with_zeros = np.zeros((np.size(array) * 4 - 3))   #-3 to remove zeros after the last number 
    
    array_with_zeros[::4] = array
    
    return array_with_zeros
    
a = np.array([1,2,3,4,5])

add_zeros(a)


array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 72. How to swap two rows of an array? (★★★)

In [217]:
a = np.random.randint(10, size=(3,3))
print(a)
a[[1,2]] = a[[2,1]]
print(a)

[[3 5 9]
 [0 0 7]
 [0 6 7]]
[[3 5 9]
 [0 6 7]
 [0 0 7]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [251]:
a = np.array([True,False,True])
a = np.random.rand(3)
a = a * -1
print(a)


[-0.15888493 -0.29530448 -0.56359984]


#### 83. How to find the most frequent value in an array?

In [232]:
a = np.array([1,2,2,3,4,5,5,5,6,6,6,6,6])
np.argmax(np.bincount(a))

6

#### 89. How to get the n largest values of an array (★★★)

In [236]:
def get_largest(array, n_largest):
    array = np.asarray(array)
    array = np.sort(array)
    return array[:-n_largest + 1 ]

a = np.array([1,2,3,4,5])
number_of_largest = 3
get_largest(a, number_of_largest)

array([1, 2, 3])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [248]:
def extract_unique_rows(array):
    array = np.asarray(array)
    unique_rows_idx = np.unique(array, axis=0, return_index=True)[1]
    return array[np.sort(unique_rows_idx)]

a = np.array([[1,2],[1,2],[4,1],[3,2]])
print(a)

extract_unique_rows(a)

[[1 2]
 [1 2]
 [4 1]
 [3 2]]


array([[1, 2],
       [4, 1],
       [3, 2]])