# Basic Operations with Matrices

In [1]:
import numpy as np


In [2]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [3]:
A = np.array([[1,2],[3,4],[5,6]])
type(A)

numpy.ndarray

In [4]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

## Shape


The shape of an array tells us the number of values for each dimension. For a 2-dimensional array, it will give us the number of rows and the number of columns. Let’s find the shape of the previous 2-dimensional matrix A. Since A is a numpy.ndarray (it was created with the array() function), we can access its shape attribute with:

In [5]:
A.shape

(3, 2)

In [6]:
x.shape

(4,)

In [7]:
len(x)

4

In [9]:
A_T = A.T
A_T

array([[1, 3, 5],
       [2, 4, 6]])

## Matrix Addition

In [10]:
B = np.array([[2,5],[7,4],[4,3]])
B

array([[2, 5],
       [7, 4],
       [4, 3]])

In [11]:
C = A + B
C

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

## Matrix Multiplication

In [13]:
A = np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
B = np.array([[2],[4]])
B

array([[2],
       [4]])

In [17]:
#C = A.dot(B)
C = np.dot(A, B)
C

array([[10],
       [22],
       [34]])

## Identity Matrices

In [18]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
IA = I.dot(A)
IA

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

## Determinant

In [20]:
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [21]:
det_M = np.linalg.det(M)
det_M

-2.0000000000000004

Determinants can be computed only from square matrices

In [22]:
M = np.array([[1,2],[3,4],[5,6]])
det_M = np.linalg.det(M)
det_M

LinAlgError: Last 2 dimensions of the array must be square

## Inverse Matrices

In [23]:
A = np.array([[3,0,2],[2,0,-2],[0,1,1]])
A

array([[ 3,  0,  2],
       [ 2,  0, -2],
       [ 0,  1,  1]])

In [24]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

In [35]:
I = A_inv.dot(A).round()
I

array([[ 1.,  0., -0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])