**TASK:** import numpy

In [1]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [2]:
x = np.array([1,2,3])

**TASK:** define (2 x 2) matrix 'A' 


In [3]:
A = np.array([[1,2],[3,4]])

**TASK:** define (2 x 2) matrix 'B'

In [4]:
B = np.array([[5,6],[7,8]])

**TASK:** check the type of 'x'

In [5]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [6]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [9]:
x.shape

(3,)

**TASK:** check the type of 'A'

In [11]:
type(A)

numpy.ndarray

**TASK:** 

In [ ]:

""""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

In [13]:
def have_same_shape(array_1, array_2):
    if array_1.shape == array_2.shape:
        return True
    else:
        print('Arrays must have the same shape!')
        return False

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [14]:
have_same_shape(A,x)

Arrays must have the same shape!


False

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [15]:
have_same_shape(A,B)

True

**TASK:** 

In [ ]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


In [31]:
def matrix_addition(A, B):
    if have_same_shape(A, B):
        C = A + B
        return C

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [32]:
matrix_addition(A,B)

array([[ 6,  8],
       [10, 12]])

**TASK:** 

In [1]:
"""
Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [43]:
def multiple_matrix_addition(lst_of_arr):
    sum_matrix = np.zeros(lst_of_arr[0].shape) 
    for array in lst_of_arr:
        sum_matrix = matrix_addition(sum_matrix, array)
        
    return sum_matrix

**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [44]:
multiple_matrix_addition([A,A,B,B,B])

array([[17., 22.],
       [27., 32.]])

**TASK:** 

In [ ]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

In [57]:
def can_multiply(array_a, array_b):
    if array_a.shape[1] == array_b.shape[0]:
        print(array_a.shape[0],",",array_b.shape[1]) 
        return True
    else:
        print('Matrices can not be multiplied')
        return False

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [48]:
can_multiply(A,B)

2 , 2


True

**TASK:**  define matrix (3 x 2) matrix C

In [49]:
C = np.zeros((3,2))
C

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [55]:
can_multiply(A,C)

False

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [51]:
can_multiply(C,A)

3 , 2


True

**TASK:** 

In [ ]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

In [52]:
def matrix_multiplication(array_a, array_b):
    if can_multiply(array_a, array_b):
        return array_a.dot(array_b)
    

**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [53]:
matrix_multiplication(C,B)

3 , 2


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [58]:
matrix_multiplication(A,C)

Matrices can not be multiplied
